version: '3.4'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nati
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
      - storage:/var/lib/mysql
volumes:
  storage:
